### ISSUE TITLE
Missing Port configuration

### ISSUE THREAD

**Issue by tinohager** [aviationexam/docker-compose-builder#131]
Hello thanks for the project!

It is possible to add on `Port` 

- host_ip: The Host IP mapping, unspecified means all network interfaces (0.0.0.0).
- name: A human-readable name for the port, used to document it's usage within the service.

Documentation
https://docs.docker.com/reference/compose-file/services/#ports

**Comment by trejjam** [comment]
Hello Tino, it's possible. Pull requests are welcome.
